# Generated by Django 6.0.4 on 2026-04-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_fecha_registro_and_more'),
        ('envios', '0003_alinear_con_pdf_sesion3'),
        ('rutas', '0004_alter_ruta_precio_base_ruta_ruta_estado_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Historial de estado', 'verbose_name_plural': 'Historiales de estado'},
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_entrega_est',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado'], name='empleado_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['estado', 'fecha_entrega_est'], name='encomienda_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['ruta', 'estado'], name='encomienda_ruta_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['remitente', 'estado'], name='encomienda_rem_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestado',
            index=models.Index(fields=['encomienda', 'fecha_cambio'], name='historial_enc_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='encomienda',
            constraint=models.CheckConstraint(condition=models.Q(('remitente', models.F('destinatario')), _negated=True), name='encomienda_partes_distintas_chk'),
        ),
    ]
