# Generated by Django 6.0.4 on 2026-04-24 00:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alinear_con_pdf_sesion3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['estado'], name='ruta_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['origen', 'destino'], name='ruta_tramo_idx'),
        ),
    ]
