# Generated by Django 6.0.4 on 2026-04-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alinear_con_pdf_sesion3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado'], name='cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellidos', 'nombres'], name='cliente_nombre_idx'),
        ),
    ]
